	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GREEN, GREEN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GREEN, BROWN, GRAY, WATER, GREEN, GREEN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, YELLOW, YELLOW, RED, GRAY, GRAY, GRAY, BROWN, RED
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, RED
	tilepal 0, YELLOW, YELLOW, RED, GRAY, GRAY, BROWN, BROWN, RED
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, RED, RED, RED
	tilepal 0, BROWN, BROWN, RED, GRAY, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, RED, BROWN, BROWN, GRAY, GREEN, WATER
	tilepal 0, GREEN, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, RED, WATER, WATER
	tilepal 1, WATER, WATER, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
