	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, BROWN, GRAY, GRAY, RED
	tilepal 0, RED, BROWN, BROWN, BROWN, BROWN, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, RED, RED, WATER, GRAY, GRAY, RED
	tilepal 0, RED, BROWN, BROWN, GRAY, BROWN, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, BROWN, RED, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, RED, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, RED, RED, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, RED, RED, RED, RED, GRAY, GRAY
	tilepal 0, RED, RED, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr
	tilepal 1, ROOF, GREEN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, BROWN, ROOF, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, BROWN, GRAY, ROOF, ROOF, BROWN
	tilepal 1, ROOF, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF
	tilepal 1, GREEN, ROOF, ROOF, ROOF, BROWN, ROOF, GREEN, GREEN
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
