	const_def
MILITARY_ATTACK EQU const_value
	const MILITARY_MOVE_1
	const MILITARY_MOVE_2
	const MILITARY_MOVE_3
	const MILITARY_MOVE_4
MILITARY_SWITCH EQU const_value
	const MILITARY_SWITCH_1
	const MILITARY_SWITCH_2
	const MILITARY_SWITCH_3
	const MILITARY_SWITCH_4
	const MILITARY_SWITCH_5
	const MILITARY_SWITCH_6
	const MILITARY_OKAY
	const MILITARY_NOT_IN_BATTLE
	const MILITARY_IDLE
	const MILITARY_STRUGGLE
	const MILITARY_RUN

	const_def
	const MILITARY_ON
	const MILITARY_ACTION_SIDE
