BackpicPalletes:	INCLUDE "gfx/trainers/Backpic.pal"

TrainerPalettes: ; b0ce
	RGB 25, 18, 12
	RGB 22, 09, 05


FalknerPalette:      INCLUDE "gfx/trainers/000.pal"
WhitneyPalette:      INCLUDE "gfx/trainers/001.pal"
BugsyPalette:        INCLUDE "gfx/trainers/002.pal"
MortyPalette:        INCLUDE "gfx/trainers/003.pal"
PrycePalette:        INCLUDE "gfx/trainers/004.pal"
JasminePalette:      INCLUDE "gfx/trainers/005.pal"
ChuckPalette:        INCLUDE "gfx/trainers/006.pal"
ClairPalette:        INCLUDE "gfx/trainers/007.pal"
Rival1Palette:       INCLUDE "gfx/trainers/008.pal"
PokemonProfPalette:  INCLUDE "gfx/trainers/009.pal"
WillPalette:         INCLUDE "gfx/trainers/010.pal"
CalPalette:          INCLUDE "gfx/trainers/011.pal"
BrunoPalette:        INCLUDE "gfx/trainers/012.pal"
KarenPalette:        INCLUDE "gfx/trainers/013.pal"
KogaPalette:         INCLUDE "gfx/trainers/014.pal"
ChampionPalette:     INCLUDE "gfx/trainers/015.pal"
BrockPalette:        INCLUDE "gfx/trainers/016.pal"
MistyPalette:        INCLUDE "gfx/trainers/017.pal"
LtSurgePalette:      INCLUDE "gfx/trainers/018.pal"
ScientistPalette:    INCLUDE "gfx/trainers/019.pal"
ErikaPalette:        INCLUDE "gfx/trainers/020.pal"
YoungsterPalette:    INCLUDE "gfx/trainers/021.pal"
SchoolboyPalette:    INCLUDE "gfx/trainers/022.pal"
BirdKeeperPalette:   INCLUDE "gfx/trainers/023.pal"
LassPalette:         INCLUDE "gfx/trainers/024.pal"
JaninePalette:       INCLUDE "gfx/trainers/025.pal"
CooltrainermPalette: INCLUDE "gfx/trainers/026.pal"
CooltrainerfPalette: INCLUDE "gfx/trainers/027.pal"
BeautyPalette:       INCLUDE "gfx/trainers/028.pal"
PokemaniacPalette:   INCLUDE "gfx/trainers/029.pal"
GruntmPalette:       INCLUDE "gfx/trainers/030.pal"
GentlemanPalette:    INCLUDE "gfx/trainers/031.pal"
SkierPalette:        INCLUDE "gfx/trainers/032.pal"
TeacherPalette:      INCLUDE "gfx/trainers/033.pal"
SabrinaPalette:      INCLUDE "gfx/trainers/034.pal"
BugCatcherPalette:   INCLUDE "gfx/trainers/035.pal"
FisherPalette:       INCLUDE "gfx/trainers/036.pal"
SwimmermPalette:     INCLUDE "gfx/trainers/037.pal"
SwimmerfPalette:     INCLUDE "gfx/trainers/038.pal"
SailorPalette:       INCLUDE "gfx/trainers/039.pal"
SuperNerdPalette:    INCLUDE "gfx/trainers/040.pal"
Rival2Palette:       INCLUDE "gfx/trainers/041.pal"
GuitaristPalette:    INCLUDE "gfx/trainers/042.pal"
HikerPalette:        INCLUDE "gfx/trainers/043.pal"
BikerPalette:        INCLUDE "gfx/trainers/044.pal"
BlainePalette:       INCLUDE "gfx/trainers/045.pal"
BurglarPalette:      INCLUDE "gfx/trainers/046.pal"
FirebreatherPalette: INCLUDE "gfx/trainers/047.pal"
JugglerPalette:      INCLUDE "gfx/trainers/048.pal"
BlackbeltTPalette:   INCLUDE "gfx/trainers/049.pal"
ExecutivemPalette:   INCLUDE "gfx/trainers/050.pal"
PsychicTPalette:     INCLUDE "gfx/trainers/051.pal"
PicnickerPalette:    INCLUDE "gfx/trainers/052.pal"
CamperPalette:       INCLUDE "gfx/trainers/053.pal"
ExecutivefPalette:   INCLUDE "gfx/trainers/054.pal"
SagePalette:         INCLUDE "gfx/trainers/055.pal"
MediumPalette:       INCLUDE "gfx/trainers/056.pal"
BoarderPalette:      INCLUDE "gfx/trainers/057.pal"
PokefanmPalette:     INCLUDE "gfx/trainers/058.pal"
KimonoGirlPalette:   INCLUDE "gfx/trainers/059.pal"
TwinsPalette:        INCLUDE "gfx/trainers/060.pal"
PokefanfPalette:     INCLUDE "gfx/trainers/061.pal"
RedPalette:          INCLUDE "gfx/trainers/062.pal"
BluePalette:         INCLUDE "gfx/trainers/063.pal"
OfficerPalette:      INCLUDE "gfx/trainers/064.pal"
GruntfPalette:       INCLUDE "gfx/trainers/065.pal"
MysticalmanPalette:  INCLUDE "gfx/trainers/066.pal"
BillPalette:         INCLUDE "gfx/trainers/067.pal"
ProfElmPalette:      INCLUDE "gfx/trainers/068.pal"
tppPcPalette:        INCLUDE "gfx/trainers/069.pal"
GiovanniPalette:     INCLUDE "gfx/trainers/070.pal"
CoolSiblingsPalette: INCLUDE "gfx/trainers/071.pal"
ChrisRBPalette:      INCLUDE "gfx/trainers/072.pal"
KrisRBPalette:       INCLUDE "gfx/trainers/073.pal"
BrockRBPalette:      INCLUDE "gfx/trainers/016.pal"
MistyRBPalette:      INCLUDE "gfx/trainers/017.pal"
; BabaPalette:         INCLUDE "gfx/trainers/074.pal"
BabaPalette:         INCLUDE "gfx/trainers/000.pal" ; Uncomment this if the above is rejected
ExecutiveEgkPalette:   INCLUDE "gfx/trainers/050.pal"

; b1de

