 	db "POUND@"
 	db "KARATE CHOP@"
 	db "DOUBLESLAP@"
 	db "GUNK SHOT@"
 	db "ZEN HEADBUTT@"
 	db "PAY DAY@"
 	db "FIRE PUNCH@"
 	db "ICE PUNCH@"
 	db "THUNDERPUNCH@"
 	db "SCRATCH@"
 	db "FAIRY WIND@"
 	db "FOCUS BLAST@"
 	db "IRON DEFENSE@"
 	db "SWORDS DANCE@"
 	db "CUT@"
 	db "GUST@"
 	db "WING ATTACK@"
 	db "WHIRLWIND@"
 	db "FLY@"
 	db "BUG BUZZ@"
 	db "SLAM@"
 	db "VINE WHIP@"
 	db "STOMP@"
 	db "DOUBLE KICK@"
 	db "MEGA KICK@"
 	db "FLARE BLITZ@"
 	db "ROLLING KICK@"
 	db "SAND ATTACK@"
 	db "HEADBUTT@"
 	db "HORN ATTACK@"
 	db "FURY ATTACK@"
 	db "HORN DRILL@"
 	db "TACKLE@"
 	db "BODY SLAM@"
 	db "WRAP@"
 	db "TAKE DOWN@"
 	db "THRASH@"
 	db "DOUBLE EDGE@"
 	db "TAIL WHIP@"
 	db "POISON STING@"
 	db "TWINEEDLE@"
 	db "PIN MISSILE@"
 	db "LEER@"
 	db "BITE@"
 	db "GROWL@"
 	db "ROAR@"
 	db "SING@"
 	db "SUPERSONIC@"
 	db "SONICBOOM@"
 	db "DISABLE@"
 	db "ACID@"
 	db "EMBER@"
 	db "FLAMETHROWER@"
 	db "MIST@"
 	db "WATER GUN@"
 	db "HYDRO PUMP@"
 	db "SURF@"
 	db "ICE BEAM@"
 	db "BLIZZARD@"
 	db "PSYBEAM@"
 	db "BUBBLEBEAM@"
 	db "AURORA BEAM@"
 	db "HYPER BEAM@"
 	db "PECK@"
 	db "DRILL PECK@"
 	db "SUBMISSION@"
 	db "HEAT WAVE@"
 	db "COUNTER@"
 	db "SEISMIC TOSS@"
 	db "STRENGTH@"
 	db "ABSORB@"
 	db "MEGA DRAIN@"
 	db "LEECH SEED@"
 	db "GROWTH@"
 	db "RAZOR LEAF@"
 	db "SOLARBEAM@"
 	db "POISONPOWDER@"
 	db "STUN SPORE@"
 	db "SLEEP POWDER@"
 	db "PETAL DANCE@"
 	db "STRING SHOT@"
 	db "DRAGON RAGE@"
 	db "FIRE SPIN@"
 	db "THUNDERSHOCK@"
 	db "THUNDERBOLT@"
 	db "THUNDER WAVE@"
 	db "THUNDER@"
 	db "ROCK THROW@"
 	db "EARTHQUAKE@"
 	db "FISSURE@"
 	db "DIG@"
 	db "TOXIC@"
 	db "CONFUSION@"
 	db "PSYCHIC@"
 	db "HYPNOSIS@"
 	db "MEDITATE@"
 	db "AGILITY@"
 	db "QUICK ATTACK@"
 	db "RAGE@"
 	db "TELEPORT@"
 	db "NIGHT SHADE@"
 	db "MIMIC@"
 	db "SCREECH@"
 	db "DOUBLE TEAM@"
 	db "RECOVER@"
 	db "HARDEN@"
 	db "MINIMIZE@"
 	db "SMOKESCREEN@"
 	db "CONFUSE RAY@"
 	db "WITHDRAW@"
 	db "DEFENSE CURL@"
 	db "BARRIER@"
 	db "LIGHT SCREEN@"
 	db "HAZE@"
 	db "REFLECT@"
 	db "FOCUS ENERGY@"
 	db "BIDE@"
 	db "METRONOME@"
 	db "MIRROR MOVE@"
 	db "SELFDESTRUCT@"
 	db "METAL SOUND@"
 	db "LICK@"
 	db "DRAGON PULSE@"
 	db "SLUDGE@"
 	db "BONE CLUB@"
 	db "FIRE BLAST@"
 	db "WATERFALL@"
 	db "CLAMP@"
 	db "SWIFT@"
 	db "AQUA JET@"
 	db "SPIKE CANNON@"
 	db "FLASH CANNON@"
 	db "AMNESIA@"
 	db "WILL-O-WISP@"
 	db "SOFTBOILED@"
 	db "HI JUMP KICK@"
 	db "GLARE@"
 	db "DREAM EATER@"
 	db "ROCK POLISH@"
 	db "SEED BOMB@"
 	db "LEECH LIFE@"
 	db "LOVELY KISS@"
 	db "SKY ATTACK@"
 	db "TRANSFORM@"
 	db "BUBBLE@"
 	db "DIZZY PUNCH@"
 	db "SPORE@"
 	db "FLASH@"
 	db "PSYWAVE@"
 	db "SPLASH@"
 	db "ACID ARMOR@"
 	db "CRABHAMMER@"
 	db "EXPLOSION@"
 	db "POISON JAB@"
 	db "BONEMERANG@"
 	db "REST@"
 	db "ROCK SLIDE@"
 	db "HYPER FANG@"
 	db "SHARPEN@"
 	db "CONVERSION@"
 	db "TRI ATTACK@"
 	db "SUPER FANG@"
 	db "SLASH@"
 	db "SUBSTITUTE@"
 	db "STRUGGLE@"
 	db "SKETCH@"
 	db "WILD CHARGE@"
 	db "THIEF@"
 	db "X SCISSOR@"
 	db "MIND READER@"
 	db "NIGHTMARE@"
 	db "FLAME WHEEL@"
 	db "IRON HEAD@"
 	db "CURSE@"
 	db "FLAIL@"
 	db "CONVERSION2@"
 	db "AEROBLAST@"
 	db "COTTON SPORE@"
 	db "REVERSAL@"
 	db "SPITE@"
 	db "POWDER SNOW@"
 	db "PROTECT@"
 	db "MACH PUNCH@"
 	db "SCARY FACE@"
 	db "FAINT ATTACK@"
 	db "SWEET KISS@"
 	db "BELLY DRUM@"
 	db "SLUDGE BOMB@"
 	db "MUD SLAP@"
 	db "OCTAZOOKA@"
 	db "SPIKES@"
 	db "ZAP CANNON@"
 	db "FORESIGHT@"
 	db "DESTINY BOND@"
 	db "PERISH SONG@"
 	db "ICY WIND@"
 	db "AIR SLASH@"
 	db "DARK PULSE@"
 	db "EARTH POWER@"
 	db "OUTRAGE@"
 	db "SANDSTORM@"
 	db "GIGA DRAIN@"
 	db "ENDURE@"
 	db "CHARM@"
 	db "ROLLOUT@"
 	db "FALSE SWIPE@"
 	db "SWAGGER@"
 	db "MILK DRINK@"
 	db "SPARK@"
 	db "FURY CUTTER@"
 	db "STEEL WING@"
 	db "MEAN LOOK@"
 	db "ATTRACT@"
 	db "SLEEP TALK@"
 	db "HEAL BELL@"
 	db "RETURN@"
 	db "PRESENT@"
 	db "DAZZLINGLEAM@"
 	db "SAFEGUARD@"
 	db "PAIN SPLIT@"
 	db "SACRED FIRE@"
 	db "MAGNITUDE@"
 	db "DYNAMICPUNCH@"
 	db "MEGAHORN@"
 	db "DRAGONBREATH@"
 	db "BATON PASS@"
 	db "ENCORE@"
 	db "PURSUIT@"
 	db "RAPID SPIN@"
 	db "NASTY PLOT@"
 	db "IRON TAIL@"
 	db "METAL CLAW@"
 	db "VITAL THROW@"
 	db "MORNING SUN@"
 	db "SYNTHESIS@"
 	db "MOONLIGHT@"
 	db "HIDDEN POWER@"
 	db "CROSS CHOP@"
 	db "TWISTER@"
 	db "RAIN DANCE@"
 	db "SUNNY DAY@"
 	db "CRUNCH@"
 	db "MIRROR COAT@"
 	db "SHADOW CLAW@"
 	db "EXTREMESPEED@"
 	db "ANCIENTPOWER@"
 	db "SHADOW BALL@"
 	db "FUTURE SIGHT@"
 	db "ROCK SMASH@"
 	db "WHIRLPOOL@"
 	db "DRILL RUN@"
 	db "MOONBLAST@"
 	db "PLAY ROUGH@"
 	db "SHEER COLD@"
