; INCBIN "gfx/misc/leaders/1.2bpp"
; INCBIN "gfx/misc/leaders/brock.2bpp"
; INCBIN "gfx/misc/leaders/2.2bpp"
; INCBIN "gfx/misc/leaders/misty.2bpp"
; INCBIN "gfx/misc/leaders/3.2bpp"
; INCBIN "gfx/misc/leaders/ltsurge.2bpp"
; INCBIN "gfx/misc/leaders/4.2bpp"
; INCBIN "gfx/misc/leaders/erika.2bpp"
; INCBIN "gfx/misc/leaders/5.2bpp"
INCBIN "gfx/misc/leaders/koga.2bpp"
; INCBIN "gfx/misc/leaders/6.2bpp"
; INCBIN "gfx/misc/leaders/sabrina.2bpp"
; INCBIN "gfx/misc/leaders/7.2bpp"
; INCBIN "gfx/misc/leaders/blaine.2bpp"
; INCBIN "gfx/misc/leaders/8.2bpp"
INCBIN "gfx/misc/leaders/giovanni.2bpp"
; INCBIN "gfx/misc/leaders/BADGES.w56.2bpp"
